### ISSUE TITLE
Updated .html format

### ISSUE THREAD

**Issue by JoramD** [bunnyhu/dcs_controls_helper#1]
It seems like DCS updated the way the .html are formatted. Which is great but it seems to have broken this program.

[Here](https://gist.github.com/JoramD0/04df87cbb75a51d2e970e692e0613b42) is a example of the "new" html format

**Comment by bunnyhu** [comment]
Thanks, you are right!

**Comment by bunnyhu** [comment]
The new release working with the modified files.
